<script setup lang="ts">
import { useRouter } from 'vue-router'

const router = useRouter()
</script>

<template>
  <div
    class="relative z-10 flex h-full w-full flex-col items-center justify-center space-y-20 text-center text-[#292D49] border-none bg-white/70 shadow-lg backdrop-blur-md px-[15%] py-4"
  >
    <div class="flex items-center justify-center flex-col space-y-12 px-[15%]">
      <img src="@/assets/citacita-b.png" alt="AI Support" class="h-20" />
      <p class="font-noto text-2xl">
        How can we <span class="text-[#C85A09DE]">support</span> you today?
      </p>
      <p class="font-noto text-xl">
        Get support with our AI Chatbot in your journey back to the workplace. Choose the agent that
        suits your needs and start your conversation with ease.
      </p>
      <p class="font-noto text-xl">
        Please note that all advice is generated by AI and should be taken with caution
      </p>
    </div>
    <!--    cards-->
    <div class="w-full flex items-stretch justify-between space-x-6 text-start">
      <div
        class="flex bg-white rounded-lg shadow-md p-6 hover:scale-105 transition-transform cursor-pointer"
        @click="router.push('/ai/resume-checker')"
      >
        <div class="flex flex-col">
          <p class="text-2xl font-bold">Resume Checker</p>
          <div class="">Get your resume checked with our AI Resume Checker</div>
        </div>
        <img src="@/assets/arrow-with-circle.png" class="h-6 inline-block ml-2" alt="arrow" />
      </div>
      <div
        class="flex items-baseline bg-white rounded-lg shadow-md p-6 hover:scale-105 transition-transform cursor-pointer"
        @click="router.push('/ai/guide')"
      >
        <div class="flex flex-col">
          <p class="text-2xl font-bold">Learn About Our Website</p>
          <div class="">Need help navigating our website? Just ask our AI Chatbot here</div>
        </div>
        <img src="@/assets/arrow-with-circle.png" class="h-6 inline-block ml-2" alt="arrow" />
      </div>
      <div
        class="flex items-baseline bg-white rounded-lg shadow-md p-6 hover:scale-105 transition-transform cursor-pointer"
        @click="router.push('/ai/mock-interview')"
      >
        <div class="flex flex-col">
          <p class="text-2xl font-bold">Mock Interview</p>
          <div class="">Practice your interview skills with our Mock Interview AI</div>
        </div>
        <img src="@/assets/arrow-with-circle.png" class="h-6 inline-block ml-2" alt="arrow" />
      </div>
    </div>
  </div>
</template>

<style></style>
